version: '3.8'

services:
  dumbdrop:
    build:
      context: ..
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ../:/app
      - /app/node_modules
      - ../local_uploads:/app/uploads
    environment:
      NODE_ENV: development
      DUMBDROP_TITLE: DumbDrop-Dev
      MAX_FILE_SIZE: 1024
      DUMBDROP_PIN: 123456
      APPRISE_MESSAGE: "[DEV] New file uploaded - {filename} ({size}), Storage used {storage}"
      APPRISE_SIZE_UNIT: auto
    # Enable container restart during development
    restart: unless-stopped
    # Add development labels
    labels:
      - "dev.dumbware.environment=development" 